#port
server:
  port: 1234
#Service name
spring:
  #  DATASOURCE MARIADB
  security:
    user:
      name: admin
      password: admin
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
        instance:
          api-path: instances
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
eureka:
  client:
    registryFetchIntervalSeconds: 60
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: false
