server:
  port: 1768
#  error:
#    include-stacktrace: never
#Eureka client config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
  instance:
    prefer-ip-address: false


zuul:
  ignoredServices: "*"
  sensitiveHeaders:
    - Authorization,Cookie,Set-Cookie,reqId,agent
  routes:
    auth:
      url: http://localhost:9004/auth
  custom-ratelimit:
    enabled: true
    repository: redis
    api-policy-list:
      - uri: /tracking/session
        http_method: post
        limit: 10
        refreshInterval: 180
        type:
          headers: token,ip

spring:
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:9999
        username: admin
        password: admin
      notify:
        mail:
          to:

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

service:
  gateway:
    request-logging:
      enabled: true
    authorization:
      enabled: true
      url: http://localhost:9004/auth/check
      token:
        length: 64
      access-token:
        length: 128
    api:
      blacklist:
      whitelist:
        - /auth/login
        - /auth/check

