#CONFIG PORT
server:
  port: 9090

# SPRING CONFIG
spring:
  boot:
    admin:
      client:
        url: http://admin-server:9999
        username: admin
        password: admin
      notify:
        mail:
          to:

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

#Eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetchRegistry: true
    instance:
      preferIpAddress: false
