#CONFIG PORT
server:
  port: 9090

# SPRING CONFIG
spring:
  boot:
    admin:
      client:
        url: http://admin-server:9090
        username: admin
        password: admin
      notify:
        mail:
          to:

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

#Eureka client config
eureka:
  client:
    registryFetchIntervalSeconds: 60
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: false
