server:
  port: 9090
spring:
  application:
    name: file-service

  boot:
    admin:
      client:
        url: http://admin-server:9090
        username: admin
        password: admin

#Eureka client config
eureka:
  client:
    registryFetchIntervalSeconds: 60
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: false
