server:
  port: 9090
spring:
  application:
    name: file-service

  boot:
    admin:
      client:
        url: http://admin-server:9090
        username: admin
        password: admin

#Eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetchRegistry: true
    instance:
      preferIpAddress: false
